### ISSUE TITLE
consider adding band select command

### ISSUE THREAD

**Issue by csylvain** [bjornekelund/ACOM-Controller#2]
would you consider adding a way to command band changes using the remote protocol?  #enhancement

**Comment by bjornekelund** [comment]
It is an simple change but I have no plans for this. Feel free to fork.

**Comment by csylvain** [comment]
okay, thanks for permission. and yes, i have reviewed the protocol and know
it should not require more than a bit of additional code.

however, i do not yet quite understand how the code is apportioned to the
source files. would you kindly name the file which contains the
implementation of the serial protocol?  the one which has the fixed byte
values used to communicate with the Acom equipment?

**Comment by bjornekelund** [comment]
First of all you should clone the repository into Visual Studio, otherwise modifying the UI parts will be very hard.  You will find all protocol related functions in MainWindow.xaml.cs
