### ISSUE TITLE
Reported PA temperature is wrong and random lock of front buttons

### ISSUE THREAD

**Issue by IU4JNR** [bjornekelund/ACOM-Controller#3]
Hi and thanks for the nice piece of software.
I purchased a brand new ACOM 1200S and the controller works as it should. It turn it off and report output power, drive,  band and vswr in accordance with the Acom1200S
However, the temperature reported is lower than the actual one (currently SW shows 24°C and the PA reports 32°C).
Randomly it happened that the front buttons were locked. 
System is Win11 (23H2, Build 22631.4541)
PC is self assembled with AMD Ryzen 5800X
Nvidia RTX 3060
128gB DDR4
2 * NVME Sabrent

**Comment by bjornekelund** [comment]
The app shows the real temperature. Recent firmware exaggerate the temperature with around 8C to make the PA run cooler.

**Comment by IU4JNR** [comment]
Thanks Bjorn,
Didn't know the trick of Acom, then I'm glad that Acom controller shows real temperature.
Max


Inviato da Outlook per Android<https://aka.ms/AAb9ysg>

________________________________
Da: Björn Ekelund ***@***.***>
Inviato: Domenica, Dicembre 8, 2024 9:04:35 PM
A: bjornekelund/ACOM-Controller ***@***.***>
Cc: Max ***@***.***>; Author ***@***.***>
Oggetto: Re: [bjornekelund/ACOM-Controller] Reported PA temperature is wrong and random lock of front buttons (Issue #3)


The app shows the real temperature. Recent firmware exaggerate the temperature with around 8C to make the PA run cooler.
